#!/bin/bash


#Remove everything in database before running dockcheck
        psql -U postgres -d postgres -c "TRUNCATE TABLE containers;"


#If exclude is present
EXCLUDE=/app/EXCLUDE
if [ -f "$EXCLUDE" ]; then
        EXCLUDE=$(</app/EXCLUDE)
        /app/dockcheck.sh -e $EXCLUDE | sed -r "s:\x1B\[[0-9;]*[mK]::g" > /app/containers_temp
        cat /app/containers_temp > /app/containers

        else
#If exclude is not present
        /app/dockcheck.sh | sed -r "s:\x1B\[[0-9;]*[mK]::g" > /app/containers_temp
        cat /app/containers_temp > /app/containers

#Insert into database with hostname + containers
        HOSTNAME=$(cat /etc/hostname)
        if grep -q '[^[:space:]]' < GotUpdates.txt; then
        cat GotUpdates.txt | while read -r line ; do
        psql -U postgres -d postgres -c "INSERT INTO CONTAINERS \
        (HOST,NAME,LATEST,ERROR,NEW) \
        VALUES('$HOSTNAME','$line','false','false','true');" > /dev/null 2>&1
        done
        fi

        if grep -q '[^[:space:]]' < NoUpdates.txt; then
        cat NoUpdates.txt | while read -r line ; do
        psql -U postgres -d postgres -c "INSERT INTO CONTAINERS \
        (HOST,NAME,LATEST,ERROR,NEW) \
        VALUES('$HOSTNAME','$line','true','false','false');" > /dev/null 2>&1
        done
        fi

        if grep -q '[^[:space:]]' < GotErrors.txt; then
        cat GotErrors.txt  | while read -r line ; do
        psql -U postgres -d postgres -c "INSERT INTO CONTAINERS \
        (HOST,NAME,LATEST,ERROR,NEW) \
        VALUES('$HOSTNAME','$line','false','true','false');" > /dev/null 2>&1
        done
        fi

fi



if [ -f "$NOTIFY_URLS" ]; then
        
        $data='psql -U postgres -d postgres -AXtqc "SELECT name FROM containers WHERE latest='true'"'
        
        
        if [ -n "$data" ]; then
                
                
                if [ -f "$NOTIFY_DEBUG" ]; then

                        sed -i '1i There is updates available for:' /app/notifymsg
                        notifymsg="$(cat /app/notifymsg | tr -d '\0')"
                        
                        apprise -vvvv -t "Dockcheck-web Notify" -b "$data" "$NOTIFY_URLS"
                else                      
                        
                        apprise -t "Dockcheck-web Notify" -b "$data" "$NOTIFY_URLS"
                        
                fi
        fi
fi






if [ $? -eq 0 ]; then echo "$(date). Cron ran without error." >> /var/log/cron.log ; else echo "$(date). Cron got errors." >> /var/log/cron.log ; fi